---
title: "Final Project"
subtitle: "Data Visualization (STAT 302)"
author: "Benedict Jung"
output:
  html_document:
    toc: true
    toc_float: true
    highlight: "tango"
editor_options: 
  chunk_output_type: console
---


```{r Load Data, echo = FALSE, message= FALSE, warning = FALSE, error= FALSE, results = "hide"}
library(tidyverse)
library(skimr)
library(ggthemes)
library(patchwork)

data2020 <- read_csv("data/kaggle_survey_2020_responses.csv")
data2019 <- read_csv("data/kaggle_survey_2019_responses.csv")
data2018 <- read_csv("data/kaggle_survey_2018_responses.csv")
data2017 <- read_csv("data/kaggle_survey_2017_responses.csv") %>% 
  mutate(Age = case_when(
    between(Age, 18,21) ~ "18-21",
    between(Age, 22,24) ~ "22-24",
    between(Age, 25,29) ~ "25-29",
    between(Age, 30,34) ~ "30-34",
    between(Age, 35,39) ~ "35-39",
    between(Age, 40,44) ~ "40-44",
    between(Age, 45,49) ~ "45-49",
    between(Age, 50,54) ~ "50-54",
    between(Age, 55,59) ~ "55-59",
    between(Age, 60,64) ~ "60-64",
    between(Age, 65,69) ~ "65-69",
    between(Age, 70,89) ~ "70+",
    between(Age, 80,89) ~ "80+"
  ))
```

<br>

```{r, echo = FALSE,message= FALSE, error= FALSE}
gender_2017_m <- data2017 %>% 
  filter(GenderSelect == "Male") %>% 
  mutate(Year = 2017) %>% 
  rename(Gender = GenderSelect) %>% 
  select(Gender, Age, Year) %>% 
  drop_na(Age)
gender_2017_f <- data2017 %>% 
  filter(GenderSelect == "Female") %>% 
  mutate(Year = 2017) %>% 
  rename(Gender = GenderSelect) %>% 
  select(Gender, Age, Year) %>% 
  drop_na(Age)
gender_2018_m <- data2018 %>% 
  filter(Q1 == "Male") %>% 
  mutate(Year = 2018) %>% 
  rename(Gender = Q1, Age = Q2) %>% 
  select(Gender, Age, Year)
gender_2018_f <- data2018 %>% 
  filter(Q1 == "Female") %>% 
  mutate(Year = 2018) %>% 
  rename(Gender = Q1, Age = Q2) %>% 
  select(Gender, Age, Year)
gender_2019_m <- data2019 %>% 
  filter(Q2 == "Male") %>% 
  mutate(Year = 2019) %>% 
  rename(Gender = Q2, Age = Q1) %>% 
  select(Gender, Age, Year)
gender_2019_f <- data2019 %>% 
  filter(Q2 == "Female") %>% 
  mutate(Year = 2019) %>% 
  rename(Gender = Q2, Age = Q1) %>% 
  select(Gender, Age, Year)
gender_2020_m <- data2020 %>% 
  filter(Q2 == "Man") %>% 
  mutate(Year = 2020) %>% 
  rename(Gender = Q2, Age = Q1) %>% 
  mutate(Gender = str_replace(Gender, "Man", "Male")) %>% 
  select(Gender, Age, Year)
gender_2020_f <- data2020 %>% 
  filter(Q2 == "Woman") %>% 
  mutate(Year = 2020) %>% 
  rename(Gender = Q2, Age = Q1) %>% 
  mutate(Gender = str_replace(Gender, "Woman", "Female")) %>% 
  select(Gender, Age, Year)

gender1 <- rbind(gender_2017_m,gender_2017_f)
gender2 <- rbind(gender_2018_m,gender_2018_f)
gender3 <- rbind(gender_2019_m,gender_2019_f)
gender4 <- rbind(gender_2020_m,gender_2020_f)
gender5 <- rbind(gender1,gender2)
gender6 <- rbind(gender3,gender4)
gender <- rbind(gender5,gender6)


ggplot(gender, aes(Age)) +
  geom_bar(aes(fill = Gender)) +
  facet_wrap(~Year, ncol = 1) +
  labs(x = "Age",
       y = "Participants",
       title = "Gender Distribution in Data Science Community") +
  scale_fill_manual(values = c("orange","grey70"))+
  theme_fivethirtyeight()+
  theme(plot.title = element_text(
                    face = "bold",
                    family = "Comic Sans MS",
                    size = 14,
                    hjust = 0.5,
                    vjust = 1.5),
        axis.title = element_text(family = "Comic Sans MS"),
        legend.title = element_text(family = "Comic Sans MS"),
        legend.text = element_text(family = "Comic Sans MS", size = 12),
        legend.position = "top",
        strip.text = element_text(family = "Comic Sans MS"),
        panel.grid.major = element_blank(),
        axis.ticks.y = element_line(),
        strip.background =  element_rect(fill = "grey90")
)


```

<br>

```{r, echo = FALSE, message= FALSE, warning = FALSE}

edc_2017 <- data2017 %>% 
  mutate(Year = 2017) %>% 
  rename(Gender = GenderSelect) %>% 
  rename(Educ = FormalEducation) %>% 
  rename(Job = CurrentJobTitleSelect) %>% 
  mutate(Educ = case_when(
    Educ == "Some college/university study without earning a bachelor's degree" ~ "Other",
    Educ == "I did not complete any formal education past high school" ~ "High school",
    Educ == "Bachelor's degree" ~ "Bachelor's degree",
    Educ == "Master's degree" ~ "Master's degree",
    Educ == "Doctoral degree" ~ "Doctoral degree",
    Educ == "Professional degree" ~ "Professional degree",
    Educ == "I prefer not to answer" ~ "Other"
  )) %>% 
  mutate(Job = case_when(
    Job == "Software Developer/Software Engineer" ~ "Software Engineer",
    Job == "Scientist/Researcher" ~ "Research Scientist",
    Job == "Researcher" ~ "Research Scientist",
    Job == "Data Miner" ~ "Data Engineer",
    Job == "Engineer" ~ "Data Engineer",
    Job == "Operations Research Practitioner" ~ "Other",
    Job == "Computer Scientist" ~ "Other",
    Job == "Predictive Modeler" ~ "Other",
    Job == "Programmer" ~ "Other",
    Job == "DBA/Database Engineer" ~ "DBA/Database Engineer",
    Job == "Data Scientist" ~ "Data Scientist",
    Job == "Business Analyst" ~ "Business Analyst",
    Job == "Other" ~ "Other",
    Job == "Data Analyst" ~ "Data Analyst",
    Job == "Machine Learning Engineer" ~ "Machine Learning Engineer",
    Job == "Statistician" ~ "Statistician"
    )) %>% 
  select(Year,Job,Educ) %>% 
  drop_na(Job,Educ)

edc_2018 <- data2018 %>% 
  mutate(Year = 2018) %>% 
  rename(Educ = Q4) %>% 
  rename(Job = Q6) %>% 
  mutate(Educ = case_when(
    Educ == "Some college/university study without earning a bachelor's degree" ~ "Other",
    Educ == "No formal education past high school" ~ "High school",
    Educ == "Bachelor’s degree" ~ "Bachelor's degree",
    Educ == "Master’s degree" ~ "Master's degree",
    Educ == "Doctoral degree" ~ "Doctoral degree",
    Educ == "Professional degree" ~ "Professional degree",
    Educ == "I prefer not to answer" ~ "Other",
    Educ == "Some college/university study without earning a bachelor’s degree"~"Other"
  )) %>% 
  mutate(Job = case_when(
    Job == "Consultant"~"Other",
    Job == "Other" ~"Other",
    Job =="Data Scientist"~"Data Scientist",
    Job =="Not employed"~"Other",
    Job =="Data Analyst"~"Data Analyst",
    Job =="Software Engineer"~"Software Engineer",
    Job =="Student"~"Other",
    Job =="Research Assistant"~"Other",
    Job =="Chief Officer"~"Other",
    Job =="Manager"~"Other",
    Job =="Research Scientist"~"Research Scientist",
    Job =="Business Analyst"~"Business Analyst",
    Job =="Data Engineer"~"Data Engineer",
    Job =="Developer Advocate"~"Other",
    Job =="Marketing Analyst"~"Other",
    Job =="Product/Project Manager"~"Other",
    Job =="Principal Investigator"~"Other",
    Job =="Salesperson"~"Other",
    Job =="DBA/Database Engineer"~"DBA/Database Engineer",
    Job =="Statistician"~"Statistician",
    Job =="Data Journalist"~"Other"
    )) %>% 
  select(Year,Job,Educ) %>% 
  drop_na(Job,Educ)

edc_2019 <- data2019 %>% 
  mutate(Year = 2019) %>% 
  rename(Educ = Q4) %>% 
  rename(Job = Q5) %>% 
  mutate(Educ = case_when(
    Educ == "Some college/university study without earning a bachelor's degree" ~ "Other",
    Educ == "No formal education past high school" ~ "High school",
    Educ == "Bachelor’s degree" ~ "Bachelor's degree",
    Educ == "Master’s degree" ~ "Master's degree",
    Educ == "Doctoral degree" ~ "Doctoral degree",
    Educ == "Professional degree" ~ "Professional degree",
    Educ == "I prefer not to answer" ~ "Other"
  )) %>% 
  mutate(Job = case_when(
    Job == "Other" ~"Other",
    Job =="Data Scientist"~"Data Scientist",
    Job =="Not employed"~"Other",
    Job =="Data Analyst"~"Data Analyst",
    Job =="Software Engineer"~"Software Engineer",
    Job =="Student"~"Other",
    Job =="Research Scientist"~"Research Scientist",
    Job =="Business Analyst"~"Business Analyst",
    Job =="Data Engineer"~"Data Engineer",
    Job =="Product/Project Manager"~"Other",
    Job =="DBA/Database Engineer"~"DBA/Database Engineer",
    Job =="Statistician"~"Statistician"
    )) %>% 
  select(Year,Job,Educ) %>% 
  drop_na(Job,Educ)

edc_2020 <- data2020 %>% 
  mutate(Year = 2020) %>% 
  rename(Educ = Q4) %>% 
  rename(Job = Q5) %>% 
  mutate(Educ = case_when(
    Educ == "Some college/university study without earning a bachelor’s degree" ~ "Other",
    Educ == "No formal education past high school" ~ "High school",
    Educ == "Bachelor’s degree" ~ "Bachelor's degree",
    Educ == "Master’s degree" ~ "Master's degree",
    Educ == "Doctoral degree" ~ "Doctoral degree",
    Educ == "Professional degree" ~ "Professional degree",
    Educ == "I prefer not to answer" ~ "Other",
    Educ == "Some college/university study without earning a bachelor’s degree" ~ "Other"
  )) %>% 
  mutate(Job = case_when(
    Job == "Other" ~"Other",
    Job == "Currently not employed" ~ "Other",
    Job == "Product/Project Manager" ~ "Other",
    Job =="Data Scientist"~"Data Scientist",
    Job =="Not employed"~"Other",
    Job =="Data Analyst"~"Data Analyst",
    Job =="Software Engineer"~"Software Engineer",
    Job =="Student"~"Other",
    Job =="Research Scientist"~"Research Scientist",
    Job =="Business Analyst"~"Business Analyst",
    Job =="Data Engineer"~"Data Engineer",
    Job =="Product/Project Manager"~"Other",
    Job =="DBA/Database Engineer"~"DBA/Database Engineer",
    Job =="Statistician"~"Statistician",
    Job == "Machine Learning Engineer" ~ "Machine Learning Engineer"
    )) %>% 
  select(Year,Job,Educ) %>% 
  drop_na(Job,Educ)


edc1 <- rbind(edc_2017, edc_2018)
edc2 <- rbind(edc_2019, edc_2020)
edc <- rbind(edc1,edc2)



ggplot(edc, aes(Year)) +
  geom_bar(fill = "orange") +
  labs(x = NULL,
       y = "Participants",
       title = "Education Level in Data Science Community") +
  facet_wrap(~Educ)+
  theme_fivethirtyeight()+
  theme(plot.title = element_text(
                    face = "bold",
                    family = "Comic Sans MS",
                    size = 14,
                    hjust = 0.5,
                    vjust = 1.5),
        axis.title = element_text(family = "Comic Sans MS"),
        legend.title = element_blank(),
        legend.text = element_text(family = "Comic Sans MS", size = 12),
        legend.position = "top",
        strip.text = element_text(family = "Comic Sans MS"),
        panel.grid.major = element_blank(),
        panel.grid.major.y = element_line(),
        axis.ticks.y = element_line(),
        strip.background =  element_rect(fill = "grey")
)
```

<br>

```{r, echo = FALSE,fig.width=7, fig.height=7}
pay2020m <- data2020 %>% 
  filter(Q2 == "Man") %>% 
  mutate(Year = 2020) %>% 
  mutate(Q2 = str_replace(Q2, "Man", "Male")) %>% 
  mutate(Q24 = case_when(
    Q24 == "$0-999" ~ "0-100k",
    Q24 == "1,000-1,999" ~ "0-100k",
    Q24 == "10,000-14,999" ~ "0-100k",
    Q24 == "100,000-124,999" ~ "100-250k",
    Q24 == "125,000-149,999" ~ "100-250k",
    Q24 == "15,000-19,999" ~ "0-100k",
    Q24 == "150,000-199,999" ~ "100-250k",
    Q24 == "2,000-2,999" ~ "0-100k",
    Q24 == "20,000-24,999" ~ "0-100k",
    Q24 == "200,000-249,999" ~ "100-250k",
    Q24 == "25,000-29,999" ~ "0-100k",
    Q24 == "250,000-299,999" ~ "250k+",
    Q24 == "3,000-3,999" ~ "0-100k",
    Q24 == "30,000-39,999" ~ "0-100k",
    Q24 == "300,000-500,000" ~ "250k+",
    Q24 == "4,000-4,999" ~ "0-100k",
    Q24 == "5,000-7,499" ~ "0-100k",
    Q24 == "50,000-59,999" ~ "0-100k",
    Q24 == "60,000-69,999" ~ "0-100k",
    Q24 == "7,500-9,999" ~ "0-100k",
    Q24 == "70,000-79,999" ~ "0-100k",
    Q24 == "80,000-89,999" ~ "0-100k",
    Q24 == "90,000-99,999" ~ "0-100k",
    Q24 == ">$500,000" ~ "250k+"
  )) %>% 
  rename(Pay = Q24) %>% 
  rename(Gender = Q2) %>% 
  select(Year,Pay,Gender) %>% 
  drop_na(Pay) %>% 
  count(Pay) %>% 
  mutate(perc = 100*(n / sum(n)),
         label = str_c(round(perc),"%",sep = "")) %>% 
  mutate(Year = "2020") %>% 
  mutate(Gender = "Male")

pay2020f <- data2020 %>% 
  filter(Q2 == "Woman") %>% 
  mutate(Year = 2020) %>% 
  mutate(Q2 = str_replace(Q2, "Woman", "Female")) %>% 
  mutate(Q24 = case_when(
    Q24 == "$0-999" ~ "0-100k",
    Q24 == "1,000-1,999" ~ "0-100k",
    Q24 == "10,000-14,999" ~ "0-100k",
    Q24 == "100,000-124,999" ~ "100-250k",
    Q24 == "125,000-149,999" ~ "100-250k",
    Q24 == "15,000-19,999" ~ "0-100k",
    Q24 == "150,000-199,999" ~ "100-250k",
    Q24 == "2,000-2,999" ~ "0-100k",
    Q24 == "20,000-24,999" ~ "0-100k",
    Q24 == "200,000-249,999" ~ "100-250k",
    Q24 == "25,000-29,999" ~ "0-100k",
    Q24 == "250,000-299,999" ~ "250k+",
    Q24 == "3,000-3,999" ~ "0-100k",
    Q24 == "30,000-39,999" ~ "0-100k",
    Q24 == "300,000-500,000" ~ "250k+",
    Q24 == "4,000-4,999" ~ "0-100k",
    Q24 == "5,000-7,499" ~ "0-100k",
    Q24 == "50,000-59,999" ~ "0-100k",
    Q24 == "60,000-69,999" ~ "0-100k",
    Q24 == "7,500-9,999" ~ "0-100k",
    Q24 == "70,000-79,999" ~ "0-100k",
    Q24 == "80,000-89,999" ~ "0-100k",
    Q24 == "90,000-99,999" ~ "0-100k",
    Q24 == ">$500,000" ~ "250k+"
  )) %>% 
  rename(Pay = Q24) %>% 
  rename(Gender = Q2) %>% 
  select(Year,Pay,Gender) %>% 
  drop_na(Pay) %>% 
  count(Pay) %>% 
  mutate(perc = 100*(n / sum(n)),
         label = str_c(round(perc),"%",sep = "")) %>% 
  mutate(Year = "2020") %>% 
  mutate(Gender = "Female")

pay2019m <- data2019 %>% 
  filter(Q2 == "Male") %>% 
  mutate(Q10 = case_when(
    Q10 == "$0-999" ~ "0-100k",
    Q10 == "1,000-1,999" ~ "0-100k",
    Q10 == "10,000-14,999" ~ "0-100k",
    Q10 == "100,000-124,999" ~ "100-250k",
    Q10 == "125,000-149,999" ~ "100-250k",
    Q10 == "15,000-19,999" ~ "0-100k",
    Q10 == "150,000-199,999" ~ "100-250k",
    Q10 == "2,000-2,999" ~ "0-100k",
    Q10 == "20,000-24,999" ~ "0-100k",
    Q10 == "200,000-249,999" ~ "100-250k",
    Q10 == "25,000-29,999" ~ "0-100k",
    Q10 == "250,000-299,999" ~ "250k+",
    Q10 == "3,000-3,999" ~ "0-100k",
    Q10 == "30,000-39,999" ~ "0-100k",
    Q10 == "300,000-500,000" ~ "250k+",
    Q10 == "4,000-4,999" ~ "0-100k",
    Q10 == "5,000-7,499" ~ "0-100k",
    Q10 == "50,000-59,999" ~ "0-100k",
    Q10 == "60,000-69,999" ~ "0-100k",
    Q10 == "7,500-9,999" ~ "0-100k",
    Q10 == "70,000-79,999" ~ "0-100k",
    Q10 == "80,000-89,999" ~ "0-100k",
    Q10 == "90,000-99,999" ~ "0-100k",
    Q10 == ">$500,000" ~ "250k+"
  )) %>% 
  rename(Pay = Q10) %>% 
  rename(Gender = Q2) %>% 
  drop_na(Pay) %>% 
  count(Pay) %>% 
  mutate(perc = 100*(n / sum(n)),
         label = str_c(round(perc),"%",sep = "")) %>% 
  mutate(Year = "2019") %>% 
  mutate(Gender = "Male")

pay2019f <- data2019 %>% 
  filter(Q2 == "Female") %>% 
  mutate(Q10 = case_when(
    Q10 == "$0-999" ~ "0-100k",
    Q10 == "1,000-1,999" ~ "0-100k",
    Q10 == "10,000-14,999" ~ "0-100k",
    Q10 == "100,000-124,999" ~ "100-250k",
    Q10 == "125,000-149,999" ~ "100-250k",
    Q10 == "15,000-19,999" ~ "0-100k",
    Q10 == "150,000-199,999" ~ "100-250k",
    Q10 == "2,000-2,999" ~ "0-100k",
    Q10 == "20,000-24,999" ~ "0-100k",
    Q10 == "200,000-249,999" ~ "100-250k",
    Q10 == "25,000-29,999" ~ "0-100k",
    Q10 == "250,000-299,999" ~ "250k+",
    Q10 == "3,000-3,999" ~ "0-100k",
    Q10 == "30,000-39,999" ~ "0-100k",
    Q10 == "300,000-500,000" ~ "250k+",
    Q10 == "4,000-4,999" ~ "0-100k",
    Q10 == "5,000-7,499" ~ "0-100k",
    Q10 == "50,000-59,999" ~ "0-100k",
    Q10 == "60,000-69,999" ~ "0-100k",
    Q10 == "7,500-9,999" ~ "0-100k",
    Q10 == "70,000-79,999" ~ "0-100k",
    Q10 == "80,000-89,999" ~ "0-100k",
    Q10 == "90,000-99,999" ~ "0-100k",
    Q10 == ">$500,000" ~ "250k+"
  )) %>% 
  rename(Pay = Q10) %>% 
  rename(Gender = Q2) %>% 
  drop_na(Pay) %>% 
  count(Pay) %>% 
  mutate(perc = 100*(n / sum(n)),
         label = str_c(round(perc),"%",sep = "")) %>% 
  mutate(Year = "2019") %>% 
  mutate(Gender = "Female")

pay2018m <- data2018 %>% 
  filter(Q1 == "Male") %>% 
  mutate(Q9 = case_when(
    Q9 == "10-20,000" ~ "0-100k",
    Q9 == "0-10,000" ~ "0-100k",
    Q9 == "20-30,000" ~ "0-100k",
    Q9 == "125-150,000" ~ "100-250k",
    Q9 == "30-40,000" ~ "0-100k",
    Q9 == "50-60,000" ~ "0-100k",
    Q9 == "100-125,000" ~ "100-250k",
    Q9 == "90-100,000" ~ "0-100k",
    Q9 == "70-80,000" ~ "0-100k",
    Q9 == "80-90,000" ~ "0-100k",
    Q9 == "60-70,000" ~ "0-100k",
    Q9 == "400-500,000" ~ "250k+",
    Q9 == "40-50,000" ~ "0-100k",
    Q9 == "150-200,000" ~ "100-250k",
    Q9 == "500,000+" ~ "250k+",
    Q9 == "300-400,000" ~ "250k+",
    Q9 == "200-250,000" ~ "100-250k",
    Q9 == "250-300,000" ~ "250k+",
    Q9 == "I do not wish to disclose my approximate yearly compensation" ~ "0-100k"
  )) %>% 
  drop_na(Q9) %>% 
  rename(Pay = Q9) %>% 
  rename(Gender = Q1) %>% 
  count(Pay) %>% 
  mutate(perc = 100*(n / sum(n)),
         label = str_c(round(perc),"%",sep = "")) %>% 
  mutate(Year = "2018") %>% 
  mutate(Gender = "Male")

pay2018f <- data2018 %>% 
  filter(Q1 == "Female") %>% 
  mutate(Q9 = case_when(
    Q9 == "10-20,000" ~ "0-100k",
    Q9 == "0-10,000" ~ "0-100k",
    Q9 == "20-30,000" ~ "0-100k",
    Q9 == "125-150,000" ~ "100-250k",
    Q9 == "30-40,000" ~ "0-100k",
    Q9 == "50-60,000" ~ "0-100k",
    Q9 == "100-125,000" ~ "100-250k",
    Q9 == "90-100,000" ~ "0-100k",
    Q9 == "70-80,000" ~ "0-100k",
    Q9 == "80-90,000" ~ "0-100k",
    Q9 == "60-70,000" ~ "0-100k",
    Q9 == "400-500,000" ~ "250k+",
    Q9 == "40-50,000" ~ "0-100k",
    Q9 == "150-200,000" ~ "100-250k",
    Q9 == "500,000+" ~ "250k+",
    Q9 == "300-400,000" ~ "250k+",
    Q9 == "200-250,000" ~ "100-250k",
    Q9 == "250-300,000" ~ "250k+",
    Q9 == "I do not wish to disclose my approximate yearly compensation" ~ "0-100k"
  )) %>% 
  drop_na(Q9) %>% 
  rename(Pay = Q9) %>% 
  rename(Gender = Q1) %>% 
  count(Pay) %>% 
  mutate(perc = 100*(n / sum(n)),
         label = str_c(round(perc),"%",sep = "")) %>% 
  mutate(Year = "2018") %>% 
  mutate(Gender = "Female")

pay1 <- rbind(pay2020m,pay2019m)
paym <- rbind(pay1,pay2018m)
pay2 <- rbind(pay2020f,pay2019f)
payf <- rbind(pay2,pay2018f)

mplot <- ggplot(paym, aes(Year, perc, fill = Pay)) +
  geom_col(width = 0.99) + 
  scale_x_discrete(limits=c(" ", "2018", "2019", "2020"))+
  theme_minimal() +
  scale_fill_manual(
    name = "Yearly Compensation",
    values = c("orange", "grey60","grey40"),
    labels = c("$0-100k","$100-250k","$250k+")
  )+
  theme(axis.text = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank(),
        plot.title = element_text(hjust = 0.5, size = 20),
        legend.position = "None",
        panel.grid = element_blank()) +
  annotate(geom = "text", label = "Male", x = 1, y = 50, size = 4,family = "Comic Sans MS") +
  annotate(geom = "text", label = "2018", x = 2, y = 50, size = 4,family = "Comic Sans MS") +
  annotate(geom = "text", label = "2019", x = 3, y = 50, size = 4,family = "Comic Sans MS") +
  annotate(geom = "text", label = "2020", x = 4, y = 50, size = 4,family = "Comic Sans MS") +
  annotate(geom = "text", label = "88.6%", x = 2, y = 80, size = 3,family = "Comic Sans MS") +
  annotate(geom = "text", label = "82.7%", x = 3, y = 80, size = 3,family = "Comic Sans MS") +
  annotate(geom = "text", label = "85.0%", x = 4, y = 80, size = 3,family = "Comic Sans MS") +
  annotate(geom = "text", label = "1.1%", x = 2, y = 1, size = 3,family = "Comic Sans MS") +
  annotate(geom = "text", label = "1.3%", x = 3, y = 1, size = 3,family = "Comic Sans MS") +
  annotate(geom = "text", label = "1.1%", x = 4, y = 1, size = 3,family = "Comic Sans MS") +
  annotate(geom = "text", label = "10.3%", x = 2, y = 10, size = 3,family = "Comic Sans MS") +
  annotate(geom = "text", label = "16.0%", x = 3, y = 10, size = 3,family = "Comic Sans MS") +
  annotate(geom = "text", label = "13.9%", x = 4, y = 10, size = 3,family = "Comic Sans MS") +
  coord_polar("y")

fplot <- ggplot(payf, aes(Year, perc, fill = Pay)) +
  geom_col(width = 0.99) + 
  scale_x_discrete(limits=c(" ", "2018", "2019", "2020"))+
  theme_minimal() +
  scale_fill_manual(
    name = "Yearly Compensation",
    values = c("orange", "grey60","grey40"),
    labels = c("$0-100k","$100-250k","$250k+")
  )+
  theme(axis.text = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank(),
        plot.title = element_text(hjust = 0.5, size = 20),
        legend.position = c(0.88,1),
        legend.title = element_text(family = "Comic Sans MS", size = 8),
        legend.text = element_text(size = "8"),
        strip.text = element_text(family = "Comic Sans MS"),
        panel.grid = element_blank()) +
  annotate(geom = "text", label = "Female", x = 1, y = 50, size = 4,family = "Comic Sans MS") +
  annotate(geom = "text", label = "2018", x = 2, y = 50, size = 4,family = "Comic Sans MS") +
  annotate(geom = "text", label = "2019", x = 3, y = 50, size = 4,family = "Comic Sans MS") +
  annotate(geom = "text", label = "2020", x = 4, y = 50, size = 4,family = "Comic Sans MS") +
  annotate(geom = "text", label = "91.5%", x = 2, y = 80, size = 3,family = "Comic Sans MS") +
  annotate(geom = "text", label = "86.6%", x = 3, y = 80, size = 3,family = "Comic Sans MS") +
  annotate(geom = "text", label = "89.6%", x = 4, y = 80, size = 3,family = "Comic Sans MS") +
  annotate(geom = "text", label = "0.6%", x = 2, y = 1, size = 3,family = "Comic Sans MS") +
  annotate(geom = "text", label = "0.6%", x = 3, y = 1, size = 3,family = "Comic Sans MS") +
  annotate(geom = "text", label = "0.6%", x = 4, y = 1, size = 3,family = "Comic Sans MS") +
  annotate(geom = "text", label = "7.9%", x = 2, y = 10, size = 3,family = "Comic Sans MS") +
  annotate(geom = "text", label = "12.9%", x = 3, y = 10, size = 3,family = "Comic Sans MS") +
  annotate(geom = "text", label = "9.8%", x = 4, y = 10, size = 3,family = "Comic Sans MS") +
  coord_polar("y")

pay_plot <- (mplot + fplot)
pay_plot + plot_annotation(
  title = "Data Science Community Annual Income (2018-2020)",
  caption = "Male vs. Female",  
  theme = theme(plot.title = element_text(
    face = "bold",
    family = "Comic Sans MS",
    size = 14), 
  plot.caption = element_text(family = "Comic Sans MS",
                              size = 10))
  )
```

<br>

```{r echo = FALSE,message= FALSE, warning = FALSE}
final2020 <- data2020 %>% 
  filter(Q3 == "United States of America", Q2 == "Woman" |Q2 == "Man") %>% 
  mutate(Year = 2020) %>% 
  mutate(Q2 = str_replace(Q2, "Man", "Male")) %>% 
  mutate(Q2 = str_replace(Q2, "Woman", "Female")) %>% 
  mutate(Q24 = case_when(
    Q24 == "$0-999" ~ 500,
    Q24 == "1,000-1,999" ~ 1500,
    Q24 == "10,000-14,999" ~ 12500,
    Q24 == "100,000-124,999" ~ 112500,
    Q24 == "125,000-149,999" ~ 137500,
    Q24 == "15,000-19,999" ~ 17500,
    Q24 == "150,000-199,999" ~ 175000,
    Q24 == "2,000-2,999" ~ 2500,
    Q24 == "20,000-24,999" ~ 22500,
    Q24 == "200,000-249,999" ~ 225000,
    Q24 == "25,000-29,999" ~ 27500,
    Q24 == "250,000-299,999" ~ 275000,
    Q24 == "3,000-3,999" ~ 3500,
    Q24 == "30,000-39,999" ~ 35000,
    Q24 == "300,000-500,000" ~ 400000,
    Q24 == "4,000-4,999" ~ 4500,
    Q24 == "5,000-7,499" ~ 6250,
    Q24 == "50,000-59,999" ~ 55000,
    Q24 == "60,000-69,999" ~ 65000,
    Q24 == "7,500-9,999" ~ 8750,
    Q24 == "70,000-79,999" ~ 75000,
    Q24 == "80,000-89,999" ~ 85000,
    Q24 == "90,000-99,999" ~ 95000,
    Q24 == ">$500,000" ~ 500000
  )) %>% 
  rename(Pay = Q24) %>% 
  rename(Job = Q5) %>%
  rename(Gender = Q2) %>%
  mutate(Job = case_when(
    Job == "Other" ~"Other",
    Job == "Currently not employed" ~ "Other",
    Job == "Product/Project Manager" ~ "Project Manager",
    Job =="Data Scientist"~"Data Scientist",
    Job =="Not employed"~"Other",
    Job =="Data Analyst"~"Data Analyst",
    Job =="Software Engineer"~"Software Engineer",
    Job =="Student"~"Other",
    Job =="Research Scientist"~"Research Scientist",
    Job =="Business Analyst"~"Business Analyst",
    Job =="Data Engineer"~"Data Engineer",
    Job =="DBA/Database Engineer"~"Other",
    Job =="Statistician"~"Statistician",
    Job == "Machine Learning Engineer" ~ "ML Engineer"
    )) %>% 
  select(Year,Gender,Pay,Job) %>% 
  drop_na(Pay) 

ggplot(final2020, aes(Job,Pay))+
  geom_boxplot(aes(fill = Gender))+
  scale_y_continuous(limits = c(0,250000),
                     breaks = seq(0,250000,20000),
                     labels = scales::comma,
                     expand = c(0,0))+
  scale_fill_manual(values = c("orange","grey70"))+
  labs(x = "Job Title",
       y = "Annual Income (US$)",
       title = "Annual Income by Job Title in the US (2020)")+
  theme_fivethirtyeight()+
  theme(plot.title = element_text(
                    face = "bold",
                    family = "Comic Sans MS",
                    size = 14,
                    hjust = 0.5,
                    vjust = 1.5),
        axis.title = element_text(family = "Comic Sans MS"),
        legend.title = element_blank(),
        legend.text = element_text(family = "Comic Sans MS", size = 12),
        legend.position = "top",
        strip.text = element_text(family = "Comic Sans MS"),
        panel.grid.major = element_blank(),
        axis.line = element_line(),
        axis.ticks.y = element_line(),
        strip.background =  element_rect(fill = "grey"),
        axis.text.x = element_text(family = "Comic Sans MS", angle = 20, size = 8),
        axis.text.y = element_text(family = "Comic Sans MS")
        )
  
```
<br>
<br>
__Data Source__
<br>
"https://www.kaggle.com/c/kaggle-survey-2020/data"

"https://www.kaggle.com/c/kaggle-survey-2019/data"

"https://www.kaggle.com/kaggle/kaggle-survey-2018"

"https://www.kaggle.com/kaggle/kaggle-survey-2017"
